# Generated by Django 5.0.4 on 2024-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
