# Generated by Django 5.0.4 on 2024-05-31 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0002_alter_acteur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='acteurpic/'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
